# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/soulsaga

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests! For now, only run tests that have been updated
      - run: 
          name: Test
          command: >
          npm test
          tests/features/timeline/CategorySelect.test.js
          tests/features/timeline/DatePicker.test.js
          tests/features/timeline/TagInput.test.js
          tests/features/timeline/TimelineEvent.test.js
          tests/features/timeline/TimelineDisplay.test.js
          tests/features/timeline/TimelineDisplayWrapper.test.js